### ISSUE TITLE
Проект получит дальнейшее развитие ?

### ISSUE THREAD

**Issue by Baltazar500** [dimuls/rkn-bypasser#3]
Привет.

Если планируете и дальше развивать свою утилиту, загляните в свой тред на рутрекере - там пачка пожеланий и комментариев относительно него. Не стал тут плодить ворох issue'ов, не зная, жив ли проект ...

**Comment by dimuls** [comment]
Да, посмотрю, спасибо

**Comment by dimuls** [comment]
Реализовал часть пожеланий, часть сделаю в будущем.
